=============================
Synth1 to Hive Likely Mapping
=============================

Baseline:
; Built by comparing latest Synth1 parameter map with Hive AdvancedSave parameter map.
; Format:
; ID ## = Synth1 ParameterName [Hive Parameter(s)] Confidence / MappingType ; Notes

[Notes]
; IMPORTANT - CHECK THAT THERE ARE NO DUPLICATES, ie, Not parameters have been used in two places as this will likely cause conflict.
; [None] items currently have no clear target in the Hive AdvancedSave map and should be ignored.

- Phaser/Chorus/Distortion/Delay: The Mix/Wet Level should only go from Dry to Mid way due to the way synth1 works, it simply has a level knob for these FX, not an actual Wet/Dry knob.
- The AnalDist, DigiDist, Deci, Ring, Comp, Phaser FX are only allowed to be active one at a time in Synth1, whereas Hive allows all to be active at once. So this needs to be taken into account when converting.
- Synth1 Phaser conversion settings: Phaser1+Phaser2 use Stoned setting in Hive. Phaser3+Phaser4 use Flanged setting in Hive.

[Oscillator / common]
ID 0   = osc1 wave button 		[Osc1.Wave]
ID 45  = osc1 FM 				[None]
ID 76  = osc1 detune 			[Osc1.Detune]
ID 1   = osc2 wave button 		[Osc2.Wave]
ID 2   = osc2 pitch 			[Osc2.Octave]
ID 3   = osc2 fine 				[Osc2.Semi]
ID 4   = osc2 track switch 		[None]
ID 5   = osc1/2 mix 			[Osc1.Volume + Osc2.Volume] But needs crossfade/balance mapping.
ID 6   = osc2 sync switch 		[None]
ID 7   = osc2 ring switch 		[Filter2.TypeSideband] Only an approximation
ID 8   = osc pulse width 		[None]
ID 9   = osc key shift 			[VCC.Trsp]

[Osc extra / sub / modulation]
; ID 10  = osc mod env switch 	[ModEnv1 + MM1.Active] ? likely requires modulation routing logic rather than one field.
; ID 11  = osc mod amount 		[MM1.Depth1 / MM1.Depth2] ? likely matrix depth, target depends on destination.
; ID 12  = osc mod attack 		[ModEnv1.Atk] ?
; ID 13  = osc mod decay 			[ModEnv1.Dec] ?
; ID 71  = osc mod dest button 	[MM1.Dest1 = Osc2.Tune] ?
ID 72  = osc common tune 		[VCC.FTun] Global tune/coarse tune approximation.
ID 91  = osc phase 				[None]
ID 95  = osc3/sub level 		[Osc1.SubVol] Osc2.SubVol needs to be zero for every converted preset.
ID 96  = osc3/sub wave button 	[Osc1.SubWave]
ID 97  = osc3/sub octave switch [Osc1.SubTune] This can be done via this hive parameter, but it needs to be a two state affair, so the Synth1 options are: (0Oct=Osc1.SubTune:0) and (-1Oct=Osc1.SubTune:-12).

[Filter]
Filter routing needs to be enabled so these are On: OSC1 SUB1 OSC2 and SUB2 is Off for all converted presets.
ID 14  = filter type button 	[Filter1.Type]
ID 15  = filter attack 			[ModEnv1.Atk]
ID 16  = filter decay 			[ModEnv1.Dec]
ID 17  = filter sustain 		[ModEnv1.Sus]
ID 18  = filter release 		[ModEnv1.Rel]
ID 19  = filter cutoff 			[Filter1.Cutoff]
ID 20  = filter resonance 		[Filter1.Res]
ID 21  = filter env amount 		[Filter1.Env]
ID 22  = filter keytrack 		[Filter1.Key]
ID 23  = filter saturation 		[Filter1.Gain]
ID 24  = filter velocity switch [ModEnv1.Vel]

[Amp]
ID 25  = amp attack 			[AmpEnv1.Atk]
ID 26  = amp decay 				[AmpEnv1.Dec]
ID 27  = amp sustain 			[AmpEnv1.Sus]
ID 28  = amp release 			[AmpEnv1.Rel]
ID 29  = amp gain 				[Main.CcOp] Uses master volume
ID 30  = amp velocity 			[AmpEnv1.Vel]

[Arp]
ID 31  = arp type button 		[ARP.Dir]
ID 32  = arp range button 		[ARP.Oct]
ID 33  = arp beat 				[ARP.CDiv + CLK.Base + CLK.Mult] Likely timing/division combination. I'm not sure how to do this, so it maybe you need the original S1 settings also, in order to convert each setting of S1 to the correct Hive setting using a mixture of these three??
ID 34  = arp gate 				[None] Only available through Seq.Gat, which isnt the same.
ID 59  = arp on/off switch 		[ARP.OnOff]

[Tempo delay]
ID 35  = tempo delay time 			[Delay.LDelay + Delay.RDelay] set both sides to related values.
ID 36  = tempo delay feedback 		[Delay.FeedBck]
ID 37  = tempo delay dry/wet mix 	[Delay.Mix]
ID 65  = tempo delay on/off switch 	[None] Could set Delay.Mix = 0 if S1 delay is set to OFF.
ID 82  = tempo delay type selector 	[Delay.Mode]
ID 83  = tempo delay spread 		[Delay.Width]
ID 98  = tempo delay tone 			[Delay.LP]

[Voice / performance]
ID 38  = voice select mono/poly/legato 	[VCC.Mode]
ID 39  = portamento time 				[VCC.Porta]
ID 40  = pitch bend range 				[VCC.PB + VCC.PBD]
ID 73  = voice unison switch 			[Osc1.Unison + Osc2.Unison] ID73 = On, then ignore it and allow the value of ID93 to take effect on Osc1/2.Unison. ID73 = Off, then set Osc1/2.Unison to 1 so it ignores the unison voicing, effectively turning Unison off on both oscillators.
ID 74  = porta auto switch 				[None] Not available. If OFF in S1, then set VCC.Porta to zero.
ID 75  = voice unison detune 			[Osc2.Detune] Use Osc2 as Unison Detune
ID 84  = voice unison spread 			[Osc1.Width + Osc2.Width] Link these to work together
ID 85  = voice unison pitch 			[None]
ID 92  = voice unison phase 			[Osc1.Trigger + Osc2.Trigger]
ID 93  = voice unison number voices 	[Osc1.Unison + Osc2.Unison] Hive links both unsion settings
ID 94  = voice polyphony 				[VCC.Voices]

[LFO 1]
; Use MM1 for LFO1
ID 41  = lfo1 destination button 	[See LFO Destinations below, use MM1 for LFO1]
ID 42  = lfo1 wave button 			[LFO1.Wave]
ID 43  = lfo1 speed 				[LFO1.Rate]
ID 44  = lfo1 amount 				[MM1.Depth1 (and MM1.Depth2 where applicable)]
ID 57  = lfo1 on/off switch 		[MM1.Active]
ID 67  = lfo1 tempo sync switch 	[None]
ID 68  = lfo1 key sync switch 		[LFO1.Trig]

[LFO 2]
; Use MM2 for LFO2
ID 47  = lfo2 wave button 		[LFO2.Wave]
ID 48  = lfo2 speed 			[LFO2.Rate]
ID 49  = lfo2 amount 			[MM2.Depth1 (and MM2.Depth2 where applicable)]
ID 58  = lfo2 on/off switch 	[MM2.Active]
ID 46  = lfo2 dest button 		[See LFO Destinations below, but use MM2 for LFO2]
ID 69  = lfo2 tempo sync switch [None]
ID 70  = lfo2 key sync switch 	[LFO2.Trig]

====================
; LFO Destinations:
====================
; Each ModMatrix has two Dest slots and some may be required for the correct conversion of LFO destination functionality.
; Items marked ** are not possible to convert so just ignore those.
Osc2 Pitch = (MM1.Dest1 = Osc2:Tune)
Osc1+2 Pitch = (MM1.Dest1 = Osc1:Tune) + (MM1.Dest2 = Osc2:Tune)
Filter Cutoff = (MM1.Dest1 = Filter1:Cutoff)
Amp Level = (MM1.Dest1 = Osc1.Volume) + (MM1.Dest2 = Osc2.Volume)
Osc2 PulseWidth = (MM1.Dest1 = Osc1.Volume)
FM = (MM1.Dest1 = LFO1.Phase) + (MM1.Dest2 = LFO2.Phase)
Pan = (MM1.Dest1 = Osc1.Pan) + (MM1.Dest2 = Osc2.Pan)

[EQ]
ID 60  = EQ tone 		[EQ.MidF]
ID 61  = EQ frequency 	[EQ.HighF + EQ.BassF]
ID 62  = EQ level 		[EQ.HighG + EQ.MidG + EQ.BassG]
ID 63  = EQ Q 			[None]
ID 90  = pan L/R 		[Osc1.Pan + Osc2.Pan]

[Chorus]
ID 66  = chorus/flanger on/off switch 	[None] Could use Chorus.Wet = 0 if the S1 Chorus is Off.
ID 64  = chorus/flanger type selector 	[Chorus.Type]
ID 52  = chorus/flanger time 			[None]
ID 53  = chorus/flanger depth 			[Chorus.Depth]
ID 54  = chorus/flanger rate 			[Chorus.Rate]
ID 55  = chorus/flanger feedback 		[None]
ID 56  = chorus/flanger level 			[Chorus.Wet]

[FX]
ID 77  = FX on/off switch 	[FX On/Off] Essentially, there are three FX: Distortion, Compressor, Phaser. Just set their switch depending on the Synth1 state. 
ID 78  = FX type selector 	[FX On/Off] Depending on which Synth1 FX is selected, then enable that FX in Hive while disabling the other two. Essentially, there are three FX: Distortion, Compressor, Phaser. This needs to work in conjunction with the above ID77 though. So if ID77 is Off, then all three FX are Off. If ID77 is On, then only the value of ID77 should be the active FX.
ID 79  = FX control 1 		[Distort.Amount / Phaser.Rate] LOW / APPROX ; type-dependent.
ID 80  = FX control 2 		[Distort.Tone / Phaser.FB] LOW / APPROX ; type-dependent.
ID 81  = FX level 			[Distort.Mix / Phaser.Wet / Comp.Amount] Distort.Mix and Phaser.Wet should not use the full range for the Hive conversion. ie, they should use a ratio of Synth1:0-127 = Hive:0-50.

[MIDI routing / matrix: S1 to Hive]
ID 50  = midi dest1 amount 	[MM5.Depth1]
ID 51  = midi dest2 amount 	[MM6.Depth2]
ID 86  = midi source 1 		[MM5.Source]
ID 87  = midi dest 1 		[MM5.Dest1] MM5.Dest2 optional
ID 88  = midi source 2 		[MM6.Source]
ID 89  = midi dest 2 		[MM6.Dest1] MM6.Dest2 optional

===========================
; Synth1 MIDI Destinations:
===========================
; This is the key to the list below, (Depth2 | Dest2) are optional depending on how it would be implemented in Hive. Some of these require two dests to work, for example, Pan requires both as there is no global Pan in Hive:
 Dest1=Osc1:Pan
 Dest2=Osc2:Pan

; Synth1 Preset Raw value = GUI Parameter Name [MM5/MM6 Source | (ID 50: Depth1=Value | Dest1) | (ID 51: Depth2=Value | Dest2)]
; Items marked with ** are not possible to convert, so are cannot be modulated, just ignore those.
; This list is equal for both Synth1 Src1 / Src2 and Hive MM5 / MM6 so can be applied to either one in the same way.
; If 2 destinations are required to emulate one Synth1 Destination, then the Depth1 and Depth2 should be set to the same value.

-1 = --- (no entry)			[Source | (Depth1 | none.assigned) | (Depth2 | none.assigned)] If a Synth1 preset has no assigned Mod Destination, set Hive to none.
76 = Osc 1 Detune 		[Source | (Depth1 | Osc1.Detune)]
45 = Osc 1 FM			[Source | (Depth1 | Filter2.Mix)] This is now actually Modulating the fake RM, not FM.
95 = Osc 1 Sub 			[Source | (Depth1 | Osc1.SubTune)]
2  = Osc 2 Pitch		[Source | (Depth1 | Osc2.Tune)]
12 = Osc Env A			[Source | (Depth1 | Dest1) | (Depth2 | Dest2)] May add later, ignore for now
13 = Osc Env D			[Source | (Depth1 | Dest1) | (Depth2 | Dest2)] May add later, ignore for now
11 = Osc Env Amount		[Source | (Depth1 | Dest1) | (Depth2 | Dest2)] May add later, ignore for now
5  = Osc Mix			[Source | (Depth1 | Osc1.Volume) | (Depth2 | Osc2.Volume)] these two need to crossfade the Osc Volumes to emulate this one.
8  = Osc Pulse Width ** Only way to accomplish this is to make it work the exact same way as 44 = LFO 1 Depth and 49 = LFO 2 Depth below, which is pointless, so ignore this one.
91 = Osc Phase Shift **

15 = Filter A			[Source | (Depth1 | ModEnv1.Atk)]
16 = Filter D			[Source | (Depth1 | ModEnv1.Dec)]
17 = Filter S			[Source | (Depth1 | ModEnv1.Sus)]
18 = Filter R			[Source | (Depth1 | ModEnv1.Rel)]
19 = Filter Frequency	[Source | (Depth1 | Filter1.Cutoff)]
20 = Filter Resonance	[Source | (Depth1 | Filter1.Res)]
21 = Filter Amount		[Source | (Depth1 | Filter1.Env)]
23 = Filter Saturation	[Source | (Depth1 | Filter1.Gain)]
22 = Filter Tracking	[Source | (Depth1 | Filter1.Key)]
25 = Amp A				[Source | (Depth1 | AmpEnv1.Atk)]
26 = Amp D				[Source | (Depth1 | AmpEnv1.Dec)]
27 = Amp S				[Source | (Depth1 | AmpEnv1.Sus)]
28 = Amp R				[Source | (Depth1 | AmpEnv1.Rel)]
29 = Amp Gain			[Source | (Depth1 | Osc1.Volume) | (Depth2 | Osc2.Volume)]

; These three FX mods need to be set depending on which FX is selected in Synth1 ID78:
79 = FX Control 1		[Source | (Depth1 | Distort.Amount or Phaser.Rate) | (Depth2 | Distort.Tone or Phaser.Phase)]
80 = FX Control 2		[Source | (Depth1 | Distort.Amount or Phaser.Rate) | (Depth2 | Distort.Tone or Phaser.Phase)]
81 = FX Level			[Source | (Depth1 | Distort.Mix) | (Depth2 | Phaser.Wet)] Synth1:0-127 but use Hive Distort.Mix:0-100 and Phaser.Wet:0-50 as fully wet values for phaser would not be correct here.

61 = EQ Frequency		[Source | (Depth1 | EQ.HighF) | (Depth2 | EQ.BassF)]
62 = EQ Level			[Source | (Depth1 | EQ.HighG) | (Depth2 | EQ.MidG)]
63 = EQ Q **
60 = EQ Tone			[Source | (Depth1 | EQ.MidF)]
90 = Pan				[Source | (Depth1 | Osc1.Pan) | (Depth2 | Osc2.Pan)]

35 = Delay Time			[Source | (Depth1 | Delay.TimeScale)]
83 = Delay Spread		[Source | (Depth1 | Delay.Width)]
36 = Delay Feedback		[Source | (Depth1 | Delay.FeedBck)]
98 = Delay Tone			[Source | (Depth1 | Delay.Lowpass)]
37 = Delay Dry/Wet		[Source | (Depth1 | Delay.Mix)]
52 = Chorus Time **
53 = Chorus Depth		[Source | (Depth1 | Chorus.Depth)]
54 = Chorus Rate		[Source | (Depth1 | Chorus.Rate)]
55 = Chorus Feedback **
56 = Chorus Level		[Source | (Depth1 | Chorus.Wet)]

39 = Porta Time			[Source | (Depth1 | VCC.Porta)]
75 = Unison Detune		[Source | (Depth1 | Osc2.Detune)]
92 = Unison Phase Shift	**
84 = Unison Spread		[Source | (Depth1 | Osc1.Width) | (Depth2 | Osc2.Width)]
85 = Unison Pitch **
34 = Arp Gate **
43 = LFO 1 Speed		[Source | (Depth1 | LFO1.Rate)]
44 = LFO 1 Depth		[Source | (Depth1 | MM1.Depth1) | (Depth2 | MM1.Depth2)]
48 = LFO 2 Speed		[Source | (Depth1 | LFO2.Rate)]
49 = LFO 2 Depth		[Source | (Depth1 | MM2.Depth1) | (Depth2 | MM2.Depth2)]